name: Create S3 Static Site

on:
  issues:
    types: [opened, closed]
  workflow_dispatch:
    inputs:
      bucket_name:
        description: "The name of the bucket to create"
        required: true
        default: "my-static-site"
  push:
    branches: [main]
    paths:
      - "s3-bucket-static/**"
jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./s3-bucket-static
      - name: Apply Terraform
        run: |
          # Use input bucket_name if available, otherwise use issue number
          BUCKET_NAME="${{ github.event.inputs.bucket_name }}"
          if [ -z "$BUCKET_NAME" ] && [ "${{ github.event_name }}" == "issues" ]; then
            BUCKET_NAME="issue-${{ github.event.issue.number }}"
          fi

          if [ -z "$BUCKET_NAME" ]; then
            echo "Error: No bucket name provided."
            exit 1
          fi

          terraform apply -auto-approve -var="bucket_name=$BUCKET_NAME"
        working-directory: ./s3-bucket-static
